name: rfw_studio
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rfw: ^1.0.29
  flutter_fancy_tree_view: ^1.6.0
  signals: ^5.3.0
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
